// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestingVGLTU.Infrastructure.DbContexts;

#nullable disable

namespace TestingVGLTU.Infrastructure.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20250503190722_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TestingVGLTU")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestingVGLTU.Accounts.Domain.Entity.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "TestingVGLTU.Accounts.Domain.Entity.Group.Name#Title", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("name");
                        });

                    b.HasKey("Id");

                    b.ToTable("groups", "TestingVGLTU");
                });

            modelBuilder.Entity("TestingVGLTU.Accounts.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Login", "TestingVGLTU.Accounts.Domain.Entity.User.Login#Login", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Login");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "TestingVGLTU.Accounts.Domain.Entity.User.Name#FullName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.Property<string>("Patronymic")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("patronymic");

                            b1.Property<string>("Surname")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("surname");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Password", "TestingVGLTU.Accounts.Domain.Entity.User.Password#Password", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("password");
                        });

                    b.HasKey("Id");

                    b.ToTable("users", "TestingVGLTU");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TestingVGLTU.ActiveTestings.Domain.Entity.ActiveTesting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsComplite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complite");

                    b.Property<Guid>("LayoutTestingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("LayoutTestingId");

                    b.ToTable("active_testing", "TestingVGLTU");
                });

            modelBuilder.Entity("TestingVGLTU.ActiveTestings.Domain.Entity.History", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActiveTestingId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsComplite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complite");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.ComplexProperty<Dictionary<string, object>>("Attemp", "TestingVGLTU.ActiveTestings.Domain.Entity.History.Attemp#Attemps", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("attemp");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ActiveTestingId");

                    b.HasIndex("StudentId");

                    b.ToTable("history", "TestingVGLTU");
                });

            modelBuilder.Entity("TestingVGLTU.ActiveTestings.Domain.Entity.UserResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HistoryId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("response");

                    b.HasKey("Id");

                    b.HasIndex("HistoryId");

                    b.HasIndex("QuestionId");

                    b.ToTable("user_response", "TestingVGLTU");
                });

            modelBuilder.Entity("TestingVGLTU.LayoutTestings.Domain.Entity.LayoutTesting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("TypeTestingId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Attemps", "TestingVGLTU.LayoutTestings.Domain.Entity.LayoutTesting.Attemps#Attemps", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("attemps");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Title", "TestingVGLTU.LayoutTestings.Domain.Entity.LayoutTesting.Title#Title", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("title");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TypeOutPut", "TestingVGLTU.LayoutTestings.Domain.Entity.LayoutTesting.TypeOutPut#TypeOutPut", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("type_out_put");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TypeTestingId");

                    b.ToTable("layouts_testings", "TestingVGLTU");
                });

            modelBuilder.Entity("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("layout_testing_id")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Scores", "TestingVGLTU.LayoutTestings.Domain.Entity.Questions.Question.Scores#Scores", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("scores");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SerialNumber", "TestingVGLTU.LayoutTestings.Domain.Entity.Questions.Question.SerialNumber#SerialNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("serial_number");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Text", "TestingVGLTU.LayoutTestings.Domain.Entity.Questions.Question.Text#Text", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasColumnType("text")
                                .HasColumnName("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("layout_testing_id");

                    b.ToTable("questions", "TestingVGLTU");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TestingVGLTU.LayoutTestings.Domain.Entity.TypeTesting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Ratio")
                        .HasColumnType("numeric")
                        .HasColumnName("ratio");

                    b.ComplexProperty<Dictionary<string, object>>("Title", "TestingVGLTU.LayoutTestings.Domain.Entity.TypeTesting.Title#Title", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("title");
                        });

                    b.HasKey("Id");

                    b.ToTable("type_testings", "TestingVGLTU");
                });

            modelBuilder.Entity("TestingVGLTU.Accounts.Domain.Entity.Student", b =>
                {
                    b.HasBaseType("TestingVGLTU.Accounts.Domain.Entity.User");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.HasIndex("GroupId");

                    b.ToTable("students", "TestingVGLTU");
                });

            modelBuilder.Entity("TestingVGLTU.Accounts.Domain.Entity.Teacher", b =>
                {
                    b.HasBaseType("TestingVGLTU.Accounts.Domain.Entity.User");

                    b.ToTable("teachers", "TestingVGLTU");
                });

            modelBuilder.Entity("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.QuestionInputNumber", b =>
                {
                    b.HasBaseType("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.Question");

                    b.Property<string>("CorrectAnswers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("correct_answers");

                    b.ToTable("questions_input_number", "TestingVGLTU");
                });

            modelBuilder.Entity("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.QuestionInputText", b =>
                {
                    b.HasBaseType("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.Question");

                    b.Property<string>("CorrectAnswers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("correct_answers");

                    b.ToTable("questions_input_text", "TestingVGLTU");
                });

            modelBuilder.Entity("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.QuestionMultipleChoice", b =>
                {
                    b.HasBaseType("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.Question");

                    b.Property<string>("AnswerOptions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answer_options");

                    b.Property<string>("CorrectAnswers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("correct_answers");

                    b.ToTable("question_multiple_choice", "TestingVGLTU");
                });

            modelBuilder.Entity("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.QuestionSingleSelection", b =>
                {
                    b.HasBaseType("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.Question");

                    b.Property<string>("AnswerOptions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answer_options");

                    b.ComplexProperty<Dictionary<string, object>>("RightAnswer", "TestingVGLTU.LayoutTestings.Domain.Entity.Questions.QuestionSingleSelection.RightAnswer#Answer", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("right_answer");
                        });

                    b.ToTable("questions_single_selection", "TestingVGLTU");
                });

            modelBuilder.Entity("TestingVGLTU.ActiveTestings.Domain.Entity.ActiveTesting", b =>
                {
                    b.HasOne("TestingVGLTU.Accounts.Domain.Entity.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingVGLTU.LayoutTestings.Domain.Entity.LayoutTesting", null)
                        .WithMany()
                        .HasForeignKey("LayoutTestingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingVGLTU.ActiveTestings.Domain.Entity.History", b =>
                {
                    b.HasOne("TestingVGLTU.ActiveTestings.Domain.Entity.ActiveTesting", null)
                        .WithMany("History")
                        .HasForeignKey("ActiveTestingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingVGLTU.Accounts.Domain.Entity.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingVGLTU.ActiveTestings.Domain.Entity.UserResponse", b =>
                {
                    b.HasOne("TestingVGLTU.ActiveTestings.Domain.Entity.History", null)
                        .WithMany("UserResponses")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingVGLTU.LayoutTestings.Domain.Entity.LayoutTesting", b =>
                {
                    b.HasOne("TestingVGLTU.Accounts.Domain.Entity.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingVGLTU.LayoutTestings.Domain.Entity.TypeTesting", "TypeTesting")
                        .WithMany()
                        .HasForeignKey("TypeTestingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeTesting");
                });

            modelBuilder.Entity("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.Question", b =>
                {
                    b.HasOne("TestingVGLTU.LayoutTestings.Domain.Entity.LayoutTesting", null)
                        .WithMany("Questions")
                        .HasForeignKey("layout_testing_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingVGLTU.Accounts.Domain.Entity.Student", b =>
                {
                    b.HasOne("TestingVGLTU.Accounts.Domain.Entity.Group", null)
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingVGLTU.Accounts.Domain.Entity.User", null)
                        .WithOne()
                        .HasForeignKey("TestingVGLTU.Accounts.Domain.Entity.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingVGLTU.Accounts.Domain.Entity.Teacher", b =>
                {
                    b.HasOne("TestingVGLTU.Accounts.Domain.Entity.User", null)
                        .WithOne()
                        .HasForeignKey("TestingVGLTU.Accounts.Domain.Entity.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.QuestionInputNumber", b =>
                {
                    b.HasOne("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.Question", null)
                        .WithOne()
                        .HasForeignKey("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.QuestionInputNumber", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.QuestionInputText", b =>
                {
                    b.HasOne("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.Question", null)
                        .WithOne()
                        .HasForeignKey("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.QuestionInputText", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.QuestionMultipleChoice", b =>
                {
                    b.HasOne("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.Question", null)
                        .WithOne()
                        .HasForeignKey("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.QuestionMultipleChoice", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.QuestionSingleSelection", b =>
                {
                    b.HasOne("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.Question", null)
                        .WithOne()
                        .HasForeignKey("TestingVGLTU.LayoutTestings.Domain.Entity.Questions.QuestionSingleSelection", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingVGLTU.Accounts.Domain.Entity.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("TestingVGLTU.ActiveTestings.Domain.Entity.ActiveTesting", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("TestingVGLTU.ActiveTestings.Domain.Entity.History", b =>
                {
                    b.Navigation("UserResponses");
                });

            modelBuilder.Entity("TestingVGLTU.LayoutTestings.Domain.Entity.LayoutTesting", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
