// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestingVGLTU.Data;

#nullable disable

namespace TestingVGLTU.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240729185324_updateModel")]
    partial class updateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestingVGLTU.Models.ActiveTesting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("TestingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TestingId");

                    b.ToTable("ActiveTesting");
                });

            modelBuilder.Entity("TestingVGLTU.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("TestingVGLTU.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Scores")
                        .HasColumnType("int");

                    b.Property<int>("TestingId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TestingId");

                    b.ToTable("Questions");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TestingVGLTU.Models.Testing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Attempts")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeTestingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TypeTestingId");

                    b.ToTable("Testings");
                });

            modelBuilder.Entity("TestingVGLTU.Models.TypeTesting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeTestings");
                });

            modelBuilder.Entity("TestingVGLTU.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TestingVGLTU.Models.UserResponsesToTests", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveTestingId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActiveTestingId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserResponsesToTests");
                });

            modelBuilder.Entity("TestingVGLTU.Models.QuestionInputNumber", b =>
                {
                    b.HasBaseType("TestingVGLTU.Models.Question");

                    b.Property<string>("CorrectAnswers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("QuestionInputNumbers");
                });

            modelBuilder.Entity("TestingVGLTU.Models.QuestionInputText", b =>
                {
                    b.HasBaseType("TestingVGLTU.Models.Question");

                    b.Property<string>("CorrectAnswers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("QuestionInputText");
                });

            modelBuilder.Entity("TestingVGLTU.Models.QuestionMultipleChoice", b =>
                {
                    b.HasBaseType("TestingVGLTU.Models.Question");

                    b.Property<string>("AnswerOptions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectAnswers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("QuestionMultipleChoices");
                });

            modelBuilder.Entity("TestingVGLTU.Models.QuestionSingleSelection", b =>
                {
                    b.HasBaseType("TestingVGLTU.Models.Question");

                    b.Property<string>("AnswerOptions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RightAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("QuestionSingleSelections");
                });

            modelBuilder.Entity("TestingVGLTU.Models.Student", b =>
                {
                    b.HasBaseType("TestingVGLTU.Models.User");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("NumberRecordBook")
                        .HasColumnType("int");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("TestingVGLTU.Models.Teacher", b =>
                {
                    b.HasBaseType("TestingVGLTU.Models.User");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("TestingVGLTU.Models.ActiveTesting", b =>
                {
                    b.HasOne("TestingVGLTU.Models.Group", "Group")
                        .WithMany("ActiveTestings")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingVGLTU.Models.Testing", "Testing")
                        .WithMany("ActiveTestings")
                        .HasForeignKey("TestingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Testing");
                });

            modelBuilder.Entity("TestingVGLTU.Models.Question", b =>
                {
                    b.HasOne("TestingVGLTU.Models.Testing", "Testing")
                        .WithMany("Questions")
                        .HasForeignKey("TestingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Testing");
                });

            modelBuilder.Entity("TestingVGLTU.Models.Testing", b =>
                {
                    b.HasOne("TestingVGLTU.Models.Teacher", "Teacher")
                        .WithMany("Testings")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingVGLTU.Models.TypeTesting", "TypeTesting")
                        .WithMany("Testings")
                        .HasForeignKey("TypeTestingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");

                    b.Navigation("TypeTesting");
                });

            modelBuilder.Entity("TestingVGLTU.Models.UserResponsesToTests", b =>
                {
                    b.HasOne("TestingVGLTU.Models.ActiveTesting", "ActiveTesting")
                        .WithMany("UserResponsesToTests")
                        .HasForeignKey("ActiveTestingId");

                    b.HasOne("TestingVGLTU.Models.Question", "Question")
                        .WithMany("UserResponsesToTests")
                        .HasForeignKey("QuestionId");

                    b.HasOne("TestingVGLTU.Models.User", "User")
                        .WithMany("UserResponsesToTests")
                        .HasForeignKey("UserId");

                    b.Navigation("ActiveTesting");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestingVGLTU.Models.QuestionInputNumber", b =>
                {
                    b.HasOne("TestingVGLTU.Models.Question", null)
                        .WithOne()
                        .HasForeignKey("TestingVGLTU.Models.QuestionInputNumber", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingVGLTU.Models.QuestionInputText", b =>
                {
                    b.HasOne("TestingVGLTU.Models.Question", null)
                        .WithOne()
                        .HasForeignKey("TestingVGLTU.Models.QuestionInputText", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingVGLTU.Models.QuestionMultipleChoice", b =>
                {
                    b.HasOne("TestingVGLTU.Models.Question", null)
                        .WithOne()
                        .HasForeignKey("TestingVGLTU.Models.QuestionMultipleChoice", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingVGLTU.Models.QuestionSingleSelection", b =>
                {
                    b.HasOne("TestingVGLTU.Models.Question", null)
                        .WithOne()
                        .HasForeignKey("TestingVGLTU.Models.QuestionSingleSelection", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingVGLTU.Models.Student", b =>
                {
                    b.HasOne("TestingVGLTU.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingVGLTU.Models.User", null)
                        .WithOne()
                        .HasForeignKey("TestingVGLTU.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TestingVGLTU.Models.Teacher", b =>
                {
                    b.HasOne("TestingVGLTU.Models.User", null)
                        .WithOne()
                        .HasForeignKey("TestingVGLTU.Models.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestingVGLTU.Models.ActiveTesting", b =>
                {
                    b.Navigation("UserResponsesToTests");
                });

            modelBuilder.Entity("TestingVGLTU.Models.Group", b =>
                {
                    b.Navigation("ActiveTestings");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("TestingVGLTU.Models.Question", b =>
                {
                    b.Navigation("UserResponsesToTests");
                });

            modelBuilder.Entity("TestingVGLTU.Models.Testing", b =>
                {
                    b.Navigation("ActiveTestings");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("TestingVGLTU.Models.TypeTesting", b =>
                {
                    b.Navigation("Testings");
                });

            modelBuilder.Entity("TestingVGLTU.Models.User", b =>
                {
                    b.Navigation("UserResponsesToTests");
                });

            modelBuilder.Entity("TestingVGLTU.Models.Teacher", b =>
                {
                    b.Navigation("Testings");
                });
#pragma warning restore 612, 618
        }
    }
}
