<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\TestingVGLTU.Framework\TestingVGLTU.Framework.csproj" />
    <ProjectReference Include="..\TestingVGLTU.ActiveTestings.Application\TestingVGLTU.ActiveTestings.Application.csproj" />
    <ProjectReference Include="..\TestingVGLTU.ActiveTestings.Contracts\TestingVGLTU.ActiveTestings.Contracts.csproj" />
  </ItemGroup>

</Project>
