<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\TestingVGLTU.Core\TestingVGLTU.Core.csproj" />
    <ProjectReference Include="..\TestingVGLTU.LayoutTestings.Domain\TestingVGLTU.LayoutTestings.Domain.csproj" />
  </ItemGroup>

</Project>
