<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\TestingVGLTU.Framework\TestingVGLTU.Framework.csproj" />
    <ProjectReference Include="..\TestingVGLTU.LayoutTestings.Application\TestingVGLTU.LayoutTestings.Application.csproj" />
    <ProjectReference Include="..\TestingVGLTU.LayoutTestings.Contracts\TestingVGLTU.LayoutTestings.Contracts.csproj" />
  </ItemGroup>

</Project>
